#!/bin/bash

set -e

# Install Python dependencies
pip install --upgrade pipenv
pipenv install --system --skip-lock

# Display installed versions
python -V
pipenv --version
jupyter --version
pip list

# Install NLTK corpora and tokenizers
# python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
