name: Main workflow
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip pipenv
          pipenv install --dev --skip-lock --system
          python -V
          pipenv --version
          pip list
      - name: Style
        run: nbqa isort notebooks/*.ipynb
      - name: Test
        run: pytest --nbval-lax notebooks/test.ipynb
